version: '2.1'

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5500:5432"
    networks:
      - net
  rabbit:
    image: "rabbitmq:3.8.2-rc.1-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - net
networks:
  net:
